### ISSUE TITLE
Psych::DisallowedClass in Admin::SourcesController#show

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1274]
rails server didn't start

ruby: 2.7.6 with rvm
branch: https://github.com/rism-digital/muscat/commit/ef7aa7441e22de6b469970862d79764b58843bc8

```
Psych::DisallowedClass in Admin::SourcesController#show
Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess
Extracted source (around line #11):
             
    elsif !source.nil?
       update YAML::load(source)
    end
  end
  

Rails.root: /home/dev/projects/muscat

Application Trace | Framework Trace | Full Trace
lib/settings.rb:11:in `initialize'
lib/editor_configuration.rb:45:in `new'
lib/editor_configuration.rb:45:in `block in squeeze'
lib/editor_configuration.rb:42:in `each'
lib/editor_configuration.rb:42:in `squeeze'
lib/editor_configuration.rb:57:in `initialize'
lib/editor_configuration.rb:452:in `new'
lib/editor_configuration.rb:452:in `block in profiles'
lib/editor_configuration.rb:451:in `each'
lib/editor_configuration.rb:451:in `profiles'
lib/editor_configuration.rb:417:in `get_show_layout'
app/admin/source.rb:73:in `show'
```
## Workaround: 

```ruby 
!source.nil?
   update YAML::load(source, permitted_classes: [ActiveSupport::HashWithIndifferentAccess, Settings])
end
```

**Comment by HirschSt** [comment]
Fixed by 
- git reset hard (reverting)
- bundle install
- rails db:migrate
